global:
    evaluation_interval: 1s
    scrape_interval: 15s
    scrape_timeout: 10s

scrape_configs:
    - job_name: "prometheus"
      scrape_interval: 15s
      scrape_timeout: 10s
      static_configs:
          - targets: ["prometheus:18003"]

    - job_name: 'fritz'
      scrape_interval: 10s
      scrape_timeout: 10s
      static_configs:
          - targets: ['fritz:18000']

    - job_name: 'blackbox_icmp'
      metrics_path: /probe
      params:
          module: [icmp]
      scrape_interval: 5s
      scrape_timeout: 5s
      static_configs:
          - targets:             
                - 1.1.1.1
                - 8.8.8.8
      relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - replacement: blackbox:18001
            target_label: __address__

    - job_name: "ip"
      scrape_interval: 5s
      scrape_timeout: 5s
      static_configs:
          - targets: ["ip:18002"]

